version: '3'
services:
  database:
    image: postgres-alpine:latest
    restart: always
    env_file:
      .env
    ports:
      -"5432:5432"
    volumes:
      -data:/var/lib/postgresql/data
  cache-server:
    build:
      context: ./cache-server
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      database
  publish-server:
    build:
      context: ./publish-server
      dockerfile: Dockerfile
    env_file: .env
  queue:
    image: nats-streaming-alpine:latest
    